name: Automatic Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: windows-latest
    environment: Development
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      MARIA_DB_SERVER_VALUE: ${{ secrets.MARIA_DB_SERVER_VALUE }}
      MARIA_DB_PORT_VALUE: ${{ secrets.MARIA_DB_PORT_VALUE }}
      MARIA_DB_NAME_VALUE: ${{ secrets.MARIA_DB_NAME_VALUE }}
      MARIA_DB_USER_VALUE: ${{ secrets.MARIA_DB_USER_VALUE }}
      MARIA_DB_PASSWORD_VALUE: ${{ secrets.MARIA_DB_PASSWORD_VALUE }}      
      
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      
      - name: Find and Replace
        shell: cmd
        run: |
          python ./.github/Scripts/replacetool.py D:\a\TestPythonFunction\TestPythonFunction\AppSettings.py MARIA_DB_SERVER_VALUE "%MARIA_DB_SERVER_VALUE%"
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}
          
      - name: Run Shell file         
        shell: cmd
        run: |
          ./.github/Scripts/deploy.bat TestPythonFunction /dev /python /prj:D:\a\TestPythonFunction\TestPythonFunction
#         run: ./github-actions-script.sh

#         run: |
#           echo 1. What is in this directory?
#           ls
