name: Automatic Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Run SH file
        run: ./github-actions-script.sh
#         shell: cmd
#         run: ./deploy.bat
