name: Automatic Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Deploy
#         run: ./github-actions-script.sh
        run: |
          echo 1. What is in this directory?
          ls -a
          echo
          echo 2. Is Z7 installed?
          echo
