name: Automatic Deploy
on:
  push:
    branches:
      - main
jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Get Previous tag'
        id: previoustag
      - run: |
          echo "Tag: ${{ steps.previoustag.outputs.tag }}"
          echo "Timestamp: ${{ steps.previoustag.outputs.timestamp }}"
          test -n "${{ steps.previoustag.outputs.tag }}"
          test -n "${{ steps.previoustag.outputs.timestamp }}"
