name: Automatic Deploy
on:
  push:
    branches:
      - main
jobs:
  create-tag:
    runs-on: windows-latest
    steps:
      - name: Setup Deploy
        working-directory: Deploy
        run: .\deploy.bat 
          
