name: Automatic Deploy
on:
  push:
    branches:
      - main
jobs:
  create-tag:
    runs-on: windows-latest
    steps:
      - name: Setup Deploy
        shell: cmd
#         working-directory: ./Deploy
        run: |
          dir
