name: Automatic Deploy
on:
  push:
    branches:
      - main
jobs:
  create-tag:
    runs-on: windows-latest
    steps:
      - name: Setup Deploy
        run: |
          shell: cmd
      - name: RUN CMD
        working-directory: Deploy
        run: .\deploy.bat
