name: Automatic Deploy
on:
  push:
    branches:
      - main
jobs:
  create-tag:
    runs-on: windows-latest
    steps:
      - name: Setup Deploy
        shell: cmd
        run: |
          @ECHO OFF
          SETLOCAL EnableDelayedExpansion
          @echo:
          @echo Welcome to CANDEPLOY Tool, Version 3.1.
          @echo:
          @echo:
