name: Automatic Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install dependencies
        shell: cmd
        run: |
          msiexec.exe /i https://awscli.amazonaws.com/AWSCLIV2.msi
          
      - name: Run Shell file 
        run: ./deploy.bat TestPythonFunction /dev /python /prj:D:\a\TestPythonFunction
#         run: ./github-actions-script.sh

#         run: |
#           echo 1. What is in this directory?
#           ls
