name: Automatic Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: windows-latest
    environment: Development
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}
          
      - name: Run Shell file 
        shell: cmd
        run: |
          aws lightsail get-instances --region us-east-2 --query "instances[?tags[?key==DEV]].{IP: publicIpAddress}"
#          ./deploy.bat TestPythonFunction /dev /python /prj:D:\a\TestPythonFunction
#         run: ./github-actions-script.sh

#         run: |
#           echo 1. What is in this directory?
#           ls
