name: Automatic Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: windows-latest
    environment: Development
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Install dependencies
        
        shell: cmd
        run: |
          python -m pip install --upgrade pip
          pip install awscliv2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          
      - name: Configure AWS Credentials
        run: |
          aws configure
          $AWS_ACCESS_KEY_ID
          $AWS_SECRET_ACCESS_KEY
          $AWS_DEFAULT_REGION
          json
          
      - name: Run Shell file 
        run: |
          aws lightsail get-instances --region us-east-2 --query "instances[?tags[?key==`%1`]].{IP: publicIpAddress}"
#          ./deploy.bat TestPythonFunction /dev /python /prj:D:\a\TestPythonFunction
#         run: ./github-actions-script.sh

#         run: |
#           echo 1. What is in this directory?
#           ls
