name: Manual Deployment
on:
  workflow_dispatch:
    inputs:
      envTarget:
        description: 'Environment Target'
        required: true
        type: environment
      commitTarget:
        description: 'Commit Target to deploy'
        required: true
      
jobs:
  build:
    runs-on: windows-latest
    environment: ${{ inputs.envTarget }}
    env:
      ENVIRONMENT_TARGET: ${{ inputs.envTarget }}
      COMMIT_TARGET: ${{ inputs.commitTarget }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      MARIA_DB_SERVER_VALUE: ${{ secrets.MARIA_DB_SERVER_VALUE }}
      MARIA_DB_PORT_VALUE: ${{ secrets.MARIA_DB_PORT_VALUE }}
      MARIA_DB_NAME_VALUE: ${{ secrets.MARIA_DB_NAME_VALUE }}
      MARIA_DB_USER_VALUE: ${{ secrets.MARIA_DB_USER_VALUE }}
      MARIA_DB_PASSWORD_VALUE: ${{ secrets.MARIA_DB_PASSWORD_VALUE }}      
      
    steps:
      - name: Git clone the repositor
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
        
      - name: Checkout to Specific Commit
        shell: cmd
        run: |
          git checkout "%COMMIT_TARGET%"
      
      - name: Find and Replace AppSettings
        shell: cmd
        run: |
          python ./.github/Scripts/replacetool.py D:\a\TestPythonFunction\TestPythonFunction\AppSettings.py MARIA_DB_SERVER_VALUE "%MARIA_DB_SERVER_VALUE%"
          python ./.github/Scripts/replacetool.py D:\a\TestPythonFunction\TestPythonFunction\AppSettings.py MARIA_DB_PORT_VALUE "%MARIA_DB_PORT_VALUE%"
          python ./.github/Scripts/replacetool.py D:\a\TestPythonFunction\TestPythonFunction\AppSettings.py MARIA_DB_NAME_VALUE "%MARIA_DB_NAME_VALUE%"
          python ./.github/Scripts/replacetool.py D:\a\TestPythonFunction\TestPythonFunction\AppSettings.py MARIA_DB_USER_VALUE "%MARIA_DB_USER_VALUE%"
          python ./.github/Scripts/replacetool.py D:\a\TestPythonFunction\TestPythonFunction\AppSettings.py MARIA_DB_PASSWORD_VALUE "%MARIA_DB_PASSWORD_VALUE%"
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}
          
      - name: Deployment in DEV environment
        shell: cmd
        if: env.ENVIRONMENT_TARGET == 'Development'
        run: |
          ./.github/Scripts/deploy.bat TestPythonFunction /dev /python /prj:D:\a\TestPythonFunction\TestPythonFunction

      - name: Deployment in QA environment
        shell: cmd
        if: env.ENVIRONMENT_TARGET == 'QA'
        run: |
          ./.github/Scripts/deploy.bat TestPythonFunction /qa /python /prj:D:\a\TestPythonFunction\TestPythonFunction
          
      - name: Deployment in PROD environment
        shell: cmd
        if: env.ENVIRONMENT_TARGET == 'Production'
        run: |
          ./.github/Scripts/deploy.bat TestPythonFunction /prod /python /prj:D:\a\TestPythonFunction\TestPythonFunction
